apiVersion: apps/v1
kind: Deployment
metadata:
  name: perf-test-influxdb
  labels:
    app: perf-test-influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perf-test-influxdb
  template:
    metadata:
      labels:
        app: perf-test-influxdb
    spec:
      containers:
        - image: influxdb
          imagePullPolicy: IfNotPresent
          name: influxdb
          volumeMounts:
          - name: config-volume
            mountPath: /etc/influxdb
          ports:
            - containerPort: 8083
              name: influx
            - containerPort: 8086
              name: api
            - containerPort: 2003
              name: graphite
      volumes:
      - name: config-volume
        configMap:
         name: influxdb-config
---
apiVersion: v1
kind: Service
metadata:
  name: perf-test-influxdb
  labels:
    app: perf-test-influxdb
spec:
  ports:
    - port: 8083
      name: http
      targetPort: 8083
    - port: 8086
      name: api
      targetPort: 8086
    - port: 2003
      name: graphite
      targetPort: 2003
  selector:
    app: perf-test-influxdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
  labels:
    app: perf-test-influxdb
data:
  influxdb.conf: |
    [meta]
      dir = "/var/lib/influxdb/meta"

    [data]
      dir = "/var/lib/influxdb/data"
      engine = "tsm1"
      wal-dir = "/var/lib/influxdb/wal"

    # Configure the graphite api
    [[graphite]]
    enabled = true
    bind-address = ":2003" # If not set, is actually set to bind-address.
    database = "perf-test"  # store graphite data in this database
